Iter13
GearFramework/urlshort pull request #15
Opened 2023-10-16 19:05 UTC by GearFramework

2023-10-21 19:52 UTC, kilchik requested changes

2023-10-21 19:52 UTC, kilchik commented on internal/pkg/storage/db/storage.go
> +func (s *Storage) GetURL(code string) (string, bool) {
Контекст следует пробрасывать из хэндлера до каждой функции, работающей с БД. Иначе при таймауте выполнения запроса к серверу соединение к БД так и будет висеть.
Несколько подвисших соединений приведут к каскадной деградации сервиса - новые запросы не смогут обрабатываться из-за нехватки соединений

2023-10-21 19:52 UTC, kilchik commented on internal/pkg/storage/db/storage.go
> +	sync.RWMutex
Зачем нужен мьютекс? DB потокобезопасен

2023-10-21 19:52 UTC, kilchik commented on internal/server/routes.go
> +	s.Router.POST("/api/shorten", func(ctx *gin.Context) { handlers.EncodeURLFromJSON(s.api, ctx) })
ctx принято передавать первым параметров в любую функцию

2023-10-22 11:29 UTC, GearFramework commented on internal/pkg/storage/db/storage.go
> +	sync.RWMutex
У меня интерфейс Storable ему должны соответствовать все методы хранения коротких урлов

2023-10-24 15:17 UTC, kilchik commented on internal/pkg/storage/db/storage.go
> +	sync.RWMutex
Правильно, поэтому тут не должно быть embedding'а, sync.RWMutex должен быть атрибутом структуры, реализующей хранилище в виде мапы, а все локи над элементами мапы должны быть инкапсулированы в методах обращения к этой структуре. Интерфейс Storable же не должен экспозить методы Lock и Unlock

2023-10-24 15:19 UTC, kilchik approved these changes

2023-10-24 15:19 UTC, kilchik commented on internal/app/encode.go
> +	app.Store.Lock()
Вот это должно уйти на уровень хранилища - слой сервиса ничего не должен знать про необходимость что-то лочить

2023-10-24 18:36 UTC, GearFramework commented on internal/pkg/storage/db/storage.go
> +	sync.RWMutex
Да, но атомарная операции получения короткого урла - проверка на существование, генерация нового, вставка в хранилище, разве если не заблочить весь этот процесс, то не будет так, что в промежуток между проверкой на существование и вставкой другая горутина "не влезет" со своим процессом? И тогда получается коллизия.

2024-05-06 20:45 UTC, merged