Iter23
GearFramework/urlshort pull request #26
Opened 2024-09-20 20:27 UTC by GearFramework

2024-09-25 22:28 UTC, avhitrov requested changes
Приоритет параметров, хранящихся в конфигурационном файле, реализован неверно. TLS норм (хотя в продакшн системе хранить секреты в репозитории ни один безопасник не разрешит).

2024-09-25 22:28 UTC, avhitrov commented on internal/config/config.go
> +		}
По ТЗ приоритет данных в конфигурационном файле - наименьший. В реализации - наивысший.

2024-09-26 05:50 UTC, GearFramework commented on internal/config/config.go
> +		}
Ошибаетесь, реализовано именно так, что сначала парсятся флаги если флага не существует, то такой параметр в конфиге будет пустым, дальше если есть флаг или переменная окружения с конфигурационным файлом, то он загружается в этот конфиг, далее флаги мапятся в конфиг и все непустые значения перекрывают значения загруженные из конфигурационного файла, далее проверяются переменные окружения и все существующие перекрывают те, что уже есть конфиге.

2024-09-26 06:15 UTC, GearFramework commented on internal/config/config.go
> +		}
Тест:

1. `go run ./main.go` конфиг пустой, вывод в консоль при старте сервиса:
```bash
Service started with flags: []
Config from flags:  {       false}
Config after mapping:  &{:8080 http://localhost:8080 info    false }
Use config:  &{:8080 http://localhost:8080 info    false }
2024/09/26 08:55:02 Use in memory urls storage
```

2. `go run ./main.go  -c config.json` добавляем в конфиг
```json
{
  "file_storage_path": "/tmp/urls_from_config.json"
}
```
Вывод в консоль при старте сервиса:
```bash
Service started with flags: [-c config.json]
Config from flags:  {      config.json false}
Reading config file: config.json
Config from file:  &{:8080 https://localhost info /tmp/urls_from_config.json  127.0.0.0/24 false }
Config after mapping:  &{:8080 https://localhost info /tmp/urls_from_config.json  127.0.0.0/24 false }
Use config:  &{:8080 https://localhost info /tmp/urls_from_config.json  127.0.0.0/24 false }
2024/09/26 08:59:38 EOF
2024/09/26 08:59:38 Use file urls storage
```
видим что загрузился конфиг, приминился параметр `file_storage_path` и все короткие урлы будут храниться в файле `/tmp/urls_from_config.json`

3. Команда: `go run ./main.go  -c config.json -f /tmp/urls_from_flag.json` 
Добавляем в конфиг:
```json
{
  "file_storage_path": "/tmp/urls_from_config.json"
}
```
Вывод в консоль при старте сервиса:
```bash
Service started with flags: [-f /tmp/urls_from_flag.json -c config.json]
Config from flags:  {   /tmp/urls_from_flag.json   config.json false}
Reading config file: config.json
Config from file:  &{:8080 https://localhost info /tmp/urls_from_config.json  127.0.0.0/24 false }
Config after mapping:  &{:8080 https://localhost info /tmp/urls_from_flag.json  127.0.0.0/24 false }
Use config:  &{:8080 https://localhost info /tmp/urls_from_flag.json  127.0.0.0/24 false }
2024/09/26 09:05:11 Use file urls storage
```
Через флаг `-f` мы указали что теперь короткие урлы будут храниться в файле `/tmp/urls.json` и в логах мы видим, что теперь значение этого флага переопределило значение в конфигурационном файле

5. Команда: `go run ./main.go  -c config.json -f /tmp/urls_from_flag.json` 
Добавляем переменную окружения:
```bash
export FILE_STORAGE_PATH="/tmp/urls_from_env.json"
```
Добавляем в конфиг:
```json
{
  "file_storage_path": "/tmp/urls_from_config.json"
}
```
Вывод в консоль при старте сервиса:
```bash
Service started with flags: [-f /tmp/urls.json -c config.json]
Config from flags:  {   /tmp/urls.json   config.json false}
Reading config file: config.json
Config from file:  &{:8080 https://localhost info /tmp/urls_from_config.json  127.0.0.0/24 false }
Config after mapping:  &{:8080 https://localhost info /tmp/urls.json  127.0.0.0/24 false }
Use config:  &{:8080 https://localhost info /tmp/urls_from_env.json  127.0.0.0/24 false }
2024/09/26 09:10:01 EOF
2024/09/26 09:10:01 Use file urls storage
```
Из лога видим, что сначала флаг `-f` переопределил значение из конфиг-файла, а потом переменная окружения переопределила значение из флага и как результат короткие урлы хранятся в `/tmp/urls_from_env.json`, т.е. все приоритеты соблюдены.

2024-10-01 18:51 UTC, avhitrov requested changes
Вот корнер-кейс:
```.\shortener.exe -a :8080 -c config.json -f=""```
В config.json:
```
{
  "file_storage_path": "/tmp/urls_from_config.json"
}
```
Полученный результат:
```
Service started with flags: [-a :8080 -c config.json -f=]
Config from flags:  {:8080     config.json false}
Reading config file: config.json
Config from file:  &{:8080 http://localhost:8080 info /tmp/urls_from_config.json  false }
Config after mapping:  &{:8080 http://localhost:8080 info /tmp/urls_from_config.json  false }
Use config:  &{:8080 http://localhost:8080 info /tmp/urls_from_config.json  false }
```
Ожидаемый результат:
```
Service started with flags: [-a :8080 -c config.json -f=]
Config from flags:  {:8080     config.json false}
Reading config file: config.json
Config from file:  &{:8080 http://localhost:8080 info /tmp/urls_from_config.json  false }
Config after mapping:  &{:8080 http://localhost:8080 info ""  false }
Use config:  &{:8080 http://localhost:8080 info ""  false }
```
Будет исправлено - сразу приму работу, так как более вопросов к исполнению нет.

2024-10-03 21:18 UTC, avhitrov approved these changes
Все замечания учтены. Отлично!

2024-10-04 17:38 UTC, merged